services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - default
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres-primary:
    image: postgres:13
    container_name: postgres-primary
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: e-commerce
    volumes:
      - data_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - default

  auth:
    build:
      context: ./server
      dockerfile: ./apps/auth/Dockerfile
      target: production
    command: sh -c "npx prisma db push && npm run start:prod:auth"
    env_file:
      - ./server/apps/auth/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    networks:
      - default

  user:
    build:
      context: ./server
      dockerfile: ./apps/user/Dockerfile
      target: production
    command: sh -c "npx prisma generate && npm run start:prod:user"
    env_file:
      - ./server/apps/user/.env
    depends_on:
      auth:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    networks:
      - default

  product:
    build:
      context: ./server
      dockerfile: ./apps/product/Dockerfile
      target: production
    command: sh -c "npx prisma generate && npm run start:prod:product"
    env_file:
      - ./server/apps/product/.env
    depends_on:
      auth:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    networks:
      - default

  inventory:
    build:
      context: ./server
      dockerfile: ./apps/inventory/Dockerfile
      target: production
    command: sh -c "npx prisma generate && npm run start:prod:inventory"
    env_file:
      - ./server/apps/inventory/.env
    depends_on:
      auth:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    networks:
      - default

  cart:
    build:
      context: ./server
      dockerfile: ./apps/cart/Dockerfile
      target: production
    command: sh -c "npx prisma generate && npm run start:prod:cart"
    env_file:
      - ./server/apps/cart/.env
    depends_on:
      auth:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    networks:
      - default

  order:
    build:
      context: ./server
      dockerfile: ./apps/order/Dockerfile
      target: production
    command: sh -c "npx prisma generate && npm run start:prod:order"
    env_file:
      - ./server/apps/order/.env
    depends_on:
      auth:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    networks:
      - default

  billing:
    build:
      context: ./server
      dockerfile: ./apps/billing/Dockerfile
      target: production
    command: sh -c "npx prisma generate && npm run start:prod:billing"
    env_file:
      - ./server/apps/billing/.env
    depends_on:
      auth:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    networks:
      - default

  gateways:
    build:
      context: ./server
      dockerfile: ./apps/root/Dockerfile
      target: production
    command: sh -c "npx prisma generate && npm run start:prod:root"
    ports:
      - "5000:5000"
    env_file:
      - ./server/apps/root/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
      auth:
        condition: service_started
      user:
        condition: service_started
      product:
        condition: service_started
      inventory:
        condition: service_started
      cart:
        condition: service_started
      order:
        condition: service_started
      billing:
        condition: service_started
    networks:
      - default

  nextjs:
    build:
      context: ./web
      dockerfile: ./Dockerfile
      target: production
    command: npm run start:standalone
    env_file:
      - ./web/.env.production
    depends_on:
      gateways:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    ports:
      - "8001:8001"
    networks:
      - default

volumes:
  data_postgres:
  rabbitmq_data:

networks:
  default:
