services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - default
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres-primary:
    image: postgres:13
    container_name: postgres-primary
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: e-commerce
    volumes:
      - data_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - default

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: sh -c "npx prisma migrate deploy && npm run start:dev auth"
    env_file:
      - ./apps/auth/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default

  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: sh -c "npx prisma migrate deploy && npm run start:dev user"
    env_file:
      - ./apps/user/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default

  product:
    build:
      context: .
      dockerfile: ./apps/product/Dockerfile
      target: development
    command: sh -c "npx prisma migrate deploy && npm run start:dev product"
    env_file:
      - ./apps/product/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default

  inventory:
    build:
      context: .
      dockerfile: ./apps/inventory/Dockerfile
      target: development
    command: sh -c "npx prisma migrate deploy && npm run start:dev inventory"
    env_file:
      - ./apps/inventory/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default

  cart:
    build:
      context: .
      dockerfile: ./apps/cart/Dockerfile
      target: development
    command: sh -c "npx prisma migrate deploy && npm run start:dev cart"
    env_file:
      - ./apps/cart/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default

  order:
    build:
      context: .
      dockerfile: ./apps/order/Dockerfile
      target: development
    command: sh -c "npx prisma migrate deploy && npm run start:dev order"
    env_file:
      - ./apps/order/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default

  billing:
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
      target: development
    command: sh -c "npx prisma migrate deploy && npm run start:dev billing"
    env_file:
      - ./apps/billing/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default

  gateways:
    build:
      context: .
      dockerfile: ./apps/root/Dockerfile
      target: development
    command: sh -c "npx prisma migrate deploy && npm run start:dev root"
    ports:
      - '5000:5000'
    env_file:
      - ./apps/root/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
      auth:
        condition: service_started
      user:
        condition: service_started
      product:
        condition: service_started
      inventory:
        condition: service_started
      cart:
        condition: service_started
      order:
        condition: service_started
      billing:
        condition: service_started

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default

volumes:
  data_postgres:
  rabbitmq_data:

networks:
  default:
