services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - default
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres-primary:
    image: postgres:13
    container_name: postgres-primary
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: e-commerce
    volumes:
      - data_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - default

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default

  gateways:
    build:
      context: .
      dockerfile: ./apps/root/Dockerfile
      target: development
    command: npm run start:dev root
    ports:
      - '4000:4000'
    env_file:
      - ./apps/root/.env
    depends_on:
      auth:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default

volumes:
  data_postgres:
  rabbitmq_data:

networks:
  default:
